# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-yaml
    -   id: check-json

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.272
    hooks:
    -   id: ruff
        args: ['--config=pyproject.toml']

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--settings-path=pyproject.toml"]

-   repo: https://github.com/python-poetry/poetry
    rev: '1.5.1'
    hooks:
    -   id: poetry-check
    -   id: poetry-export
        args: ["--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt"]
    -   id: poetry-export
        args: ["--with", "dev", "--without-hashes", "-f", "requirements.txt", "-o", "requirements_dev.txt"]
    -   id: poetry-lock
        stages: [push]

-   repo: local
    hooks:

    -   id: radon
        name: radon
        entry: bash -c 'radon cc -nf src | awk -v t=f "$3 > t {print}" && exit 1 || exit 0'
        language: system
        types: [python]
        pass_filenames: False

    -   id: bandit
        name: bandit
        entry: bandit -r src/ -lll
        language: system
        types: [python]
        pass_filenames: false

    -   id: pytest
        name: Pytest
        entry: pytest -v
        pass_filenames: false
        language: system
        types: [python]
        stages: [push]
